from datetime import datetime

def generate_referral_letter(data: dict, risk_level: str, summary: str) -> str:
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    letter = f"""
URGENT MEDICAL REFERRAL

Date: {date_str}
Patient Name: {data.get('patient_name', 'Unknown')}
Age: {data.get('age', 'N/A')}
Gestational Week: {data.get('gestational_week', 'N/A')}

Vitals:
BP: {data.get('blood_pressure_sys', 'N/A')} / {data.get('blood_pressure_dia', 'N/A')}

Symptoms Reported:
{', '.join(data.get('symptoms', ['None reported']))}

Observation Notes:
{data.get('observation_notes', 'None')}

Risk Assessment: {risk_level}
Summary: {summary}

Referred by: SANA Community Health Worker App
Reason for Referral: Suspected complication requiring clinical evaluation.

[System Disclaimer: This letter was auto-generated by a CHW support tool and does not constitute a formal diagnosis.]
    """.strip()
    
    return letter
